### ISSUE TITLE
mdtest does not seem to scale past 16 nodes

### ISSUE THREAD

**Issue by ghost** [hpc/ior#40] opened 2018-03-15 14:16 UTC
I am running mdtest against GPFS storage and having an odd problem when it comes to scaling out the test to anything past 16 client nodes. Running on 512 cores on 16 clients I get file stat and file read results of ~4 million ops/sec. If I run the same test (same command like arguments to mdtest, same -np to MPI) on 17 nodes, the file stat results drop to ~67K ops/sec and file read drops to ~168K ops/sec. Is there any limitation with the software that would cause this test not to scale?

**Comment by glennklockwood** [comment] 2018-03-15 16:52
There shouldn't be any scalability issues caused by the mdtest software since there is very little synchronization between each MPI rank.  The fact that mdtest works, but just not as well, at larger scales sounds like you might have found a legitimate scaling issue in your file system.

If you post the full command line you're using to invoke mdtest, I can try testing at 16 and 17 nodes on a few of my file systems to confirm that there's no software issue.

**Comment by mjarsulic** [comment] 2018-03-15 17:01
mpirun -np 512 -machinefile machs ./mdtest -d /data/mdtest/ -R12345 -i 2 -n 1024 -N 64 -F -u -v

machs either contains 16 nodes or 17 nodes. I do not change the number of processes.

**Comment by glennklockwood** [comment] 2018-03-16 21:18
If you aren't changing the number of processes, you are causing load imbalance in the case of 512 processes over 17 nodes (fifteen nodes get 30 processes per node, two get 31 processes per node--assuming round-robin placement).

Try running your scaling tests with a fixed number of processes per node (e.g., `-np 544` for the 17-node case) to see if you get closer to your 4m ops/sec.

**Comment by JulianKunkel** [comment] 2018-06-29 18:55
I would close this issue, the user became a Ghost...

**Closed** 2018-07-02 17:01 UTC
