### ISSUE TITLE
Scripts cannot contain comments less than 3 characters long

### ISSUE THREAD

**Issue by parkeraddison** [hpc/ior#368] opened 2021-05-04 19:00 UTC
When using an IOR script, commented lines cannot be less than 3 characters long without causing an error. For example, the following script results in the error `Invalid option substring string: "" in "#\n"`:
```
# These are some comments at the top of the file. This is the end of my paragraph.
#
# Here's a second paragraph of comments, but the above line is invalid!
IOR START
    ...
RUN
IOR END
```

Admittedly this is a very tiny issue, but probably just needs a very tiny fix in the logic below
https://github.com/hpc/ior/blob/0ed2dc318724846b33237080442eac9fae528e04/src/parse_options.c#L274-L290

**Comment by JulianKunkel** [comment] 2021-05-05 06:50
Hi, thanks for reporting, when I run $ ior -f script 
with the following script on the current main branch, I receive a valid output.
```
# These are some comments at the top of the file. This is the end of my paragraph.
#
# Here's a second paragraph of comments, but the above line is invalid!
IOR START
RUN
IOR STOP
```

**Comment by parkeraddison** [comment] 2021-05-05 19:15
Whoops, forgive me -- I butchered my example when I cleaned up my script. You're right that previous example runs just fine. It's only if the comment is *after* IOR START (where the parameter parsing starts to happen) that an issue arises.

Revised example script:
```
IOR START
# Here is a comment.
#
# New paragraph. Above is invalid
RUN
IOR STOP
```

This results in the invalid option error. Tested on both 3.3.0 (release) and 3.4.0+dev (main).

**Comment by JulianKunkel** [comment] 2021-05-06 10:56
I believe the issue is resolved with the bugfix thanks for the report.

**Closed** 2022-07-19 19:21 UTC
Labels: bug, backport
